### ISSUE TITLE
`helm get release-name` hang

### ISSUE THREAD

**Issue by hanqiuzh** [IBM/kui#2048]
**Describe the bug**
`helm get release-name` hang

**Steps to reproduce the behavior**

1. create a chart `helm create mychart`
2. install the chart with a value set ` helm install --set replicaCount=2 --name myrelease mychart`
3. run `helm get myrelease`
4. See error, it hangs

I also ran it with webpack/proxy mode, and got errors on proxy:
```
(node:525) UnhandledPromiseRejectionWarning: YAMLException: duplicated mapping key at line 23, column 1:
    replicaCount: 2
    ^
    at generateError (/kui-proxy/kui/node_modules/js-yaml/lib/js-yaml/loader.js:167:10)
    at throwError (/kui-proxy/kui/node_modules/js-yaml/lib/js-yaml/loader.js:173:9)
    at storeMappingPair (/kui-proxy/kui/node_modules/js-yaml/lib/js-yaml/loader.js:335:7)
    at readBlockMapping (/kui-proxy/kui/node_modules/js-yaml/lib/js-yaml/loader.js:1098:9)
    at composeNode (/kui-proxy/kui/node_modules/js-yaml/lib/js-yaml/loader.js:1359:12)
    at readDocument (/kui-proxy/kui/node_modules/js-yaml/lib/js-yaml/loader.js:1519:3)
    at loadDocuments (/kui-proxy/kui/node_modules/js-yaml/lib/js-yaml/loader.js:1575:5)
    at load (/kui-proxy/kui/node_modules/js-yaml/lib/js-yaml/loader.js:1596:19)
    at safeLoad (/kui-proxy/kui/node_modules/js-yaml/lib/js-yaml/loader.js:1618:10)
    at Object.<anonymous> (/kui-proxy/kui/node_modules/@kui-shell/plugin-k8s/lib/controller/kubectl.js:61:12)
```

Guess it's because `js-yaml.safeLoad` doesn't support separated yaml files (`---`).

**Expected behavior**
Return a beautiful yaml file in sidecar

**System**

- Kui version: Latest (last pull on 07/16/2019)
- Operating system: Mac OS

**Comment by myan9** [comment]
Confirmed. I guess your guess is right.
