### ISSUE TITLE
Investigate the OpenwhiskError in app invoke

### ISSUE THREAD

**Issue by myan9** [IBM/kui#32]
The following error log appears everywhere with app invoke but the invocation result is fine.

kui/app/plugins/modules/openwhisk/plugin/lib/cmds/openwhisk-core.js 512:20
```
 TypeError: Cannot read property 'name' of undefined
    at Object.invoke (/Users/mengting.yan1ibm.com/Documents/GitHub/kui/app/plugins/modules/openwhisk/plugin/lib/cmds/openwhisk-core.js:912:65)
    at entity (/Users/mengting.yan1ibm.com/Documents/GitHub/kui/app/plugins/modules/openwhisk/plugin/lib/cmds/openwhisk-core.js:509:51)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
https://travis-ci.com/IBM/kui/jobs/162066066#L2903

**Comment by myan9** [comment]
This issue does not happen now.
