### ISSUE TITLE
grid --ui prints out error message on console

### ISSUE THREAD

**Issue by starpit** [IBM/kui#411]
this only affects launching the grid command from a headless build. for these builds, the `uuid` module is not available, but also not needed (as headless delegates the command to electron); however, we are not properly squashing the innocuous headless failure (innocuous, because control has already been handed off to electron)

```bash
/bin/kui grid
prequire error plugin-grid { Error: Cannot find module 'uuid'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    ...
```

the grid UI comes up properly, but we aren't properly squashing these (well-handled) errors

**Comment by starpit** [comment]
i think this has been resolved
