### ISSUE TITLE
ibmcloud-plugin test fails on Ubuntu 16.04 as well as RHEL 7.7/8.2

### ISSUE THREAD

**Issue by amitsadaphule** [IBM/kui#6095]
**System**
OS: Ubuntu16.04/RHEL7.7/RHEL8.2
Platform: x86
Kui version: v8.12.2
node version: v12.16.1
npm version: 6.13.4

**Describe the bug**
The test `should get default namespace via ibmcloud kui ${kubectl}` related to ibmcloud-plugin in file `plugins/plugin-kubectl/src/test/k8s-popup/a-ibmcloud-plugin.ts` fails.

**Steps to reproduce the behavior**

```
wget https://golang.org/dl/go1.15.3.linux-amd64.tar.gz
tar xzf go1.15.3.linux-amd64.tar.gz
export PATH=$PATH:`pwd`/go/bin
wget https://clis.cloud.ibm.com/download/bluemix-cli/1.2.3/linux64/archive
tar xzf archive
export PATH=$PATH:`pwd`/IBM_Cloud_CLI/
cd kui/tools/go/ibmcloud/
make
make install

[root@p00XvmYY kui]# ibmcloud plugin show kui

Plugin Name                              kui
Plugin Version                           8.12.2
Plugin SDK Version                       0.4.0
Minimal IBM Cloud CLI version required   N/A

Commands:
kui   Kui Visual Terminal

cd ../../../
sed -i 's/{plugin-\*,core,client}/{plugin-\*,core,client}\/\*/g' packages/test/bin/runTest.sh
export LAYER=k8s-popup/a-ibmcloud-plugin.js
npm run testv2
```

**Expected behavior**
The test should PASS.

**Error log**
```
> kui-shell@8.12.0 testv2 /root/amit_sadaphule/kui
> export MONOREPO_MODE=true; cd packages/test && npm run testv2


> @kui-shell/test@8.12.2 testv2 /root/amit_sadaphule/kui/packages/test
> ./bin/runMochaLayersv2.sh

running in monorepo /root/amit_sadaphule/kui/packages/test/bin/../../..
Using WEBPACK_CLIENT_URL=http://localhost:9080/index.html
find: warning: you have specified the -maxdepth option after a non-option argument -path, but options are not positional (-maxdepth affects tests specified before it as well as those specified after it).  Please specify options before other arguments.

Running these test suites: /root/amit_sadaphule/kui/packages/test/bin/../../../node_modules/@kui-shell/plugin-kubectl/dist/test/k8s-popup/a-ibmcloud-plugin.js


  ibmcloud kui
tee-to-file content:
tee-to-file content:
tee-to-file content:
tee-to-file content:
tee-to-file content:
tee-to-file content:
tee-to-file content:
tee-to-file content:
tee-to-file content:
tee-to-file content:
tee-to-file content:
tee-to-file content:
pollForEndMarker still waiting 0
tee-to-file content:
pollForEndMarker still waiting 0
tee-to-file content:
pollForEndMarker still waiting 0
tee-to-file content:
pollForEndMarker still waiting 0
tee-to-file content:
pollForEndMarker still waiting 0
tee-to-file content:
pollForEndMarker still waiting 0
tee-to-file content:
pollForEndMarker still waiting 0
tee-to-file content:
pollForEndMarker still waiting 0
tee-to-file content:
pollForEndMarker still waiting 0
tee-to-file content:
pollForEndMarker still waiting 0
tee-to-file content:
pollForEndMarker still waiting 0
tee-to-file content:
pollForEndMarker still waiting 0
tee-to-file content:
pollForEndMarker still waiting 0
tee-to-file content:
pollForEndMarker still waiting 0
tee-to-file content:
pollForEndMarker still waiting 0
tee-to-file content:
pollForEndMarker still waiting 0
tee-to-file content:
pollForEndMarker still waiting 0
tee-to-file content:
pollForEndMarker still waiting 0
tee-to-file content:
pollForEndMarker still waiting 0
tee-to-file content:
pollForEndMarker still waiting 0
tee-to-file content:
pollForEndMarker still waiting 0
tee-to-file content:
pollForEndMarker still waiting 0
tee-to-file content:
pollForEndMarker still waiting 0
tee-to-file content:
pollForEndMarker still waiting 0
tee-to-file content:
pollForEndMarker still waiting 0
tee-to-file content:
pollForEndMarker still waiting 0
tee-to-file content:
pollForEndMarker still waiting 0
tee-to-file content:
pollForEndMarker still waiting 0
tee-to-file content:
pollForEndMarker still waiting 0
tee-to-file content:
pollForEndMarker still waiting 0
tee-to-file content:
pollForEndMarker still waiting 0
tee-to-file content:
pollForEndMarker still waiting 0
tee-to-file content:
pollForEndMarker still waiting 0
tee-to-file content:
pollForEndMarker still waiting 0
tee-to-file content:
pollForEndMarker still waiting 0
tee-to-file content:
pollForEndMarker still waiting 0
tee-to-file content:
pollForEndMarker still waiting 0
tee-to-file content:
pollForEndMarker still waiting 0
tee-to-file content:
pollForEndMarker still waiting 0
tee-to-file content:
pollForEndMarker still waiting 0
tee-to-file content:
pollForEndMarker still waiting 0
tee-to-file content:
pollForEndMarker still waiting 0
tee-to-file content:
pollForEndMarker still waiting 0
tee-to-file content:
pollForEndMarker still waiting 0
tee-to-file content:
pollForEndMarker still waiting 0
tee-to-file content:
pollForEndMarker still waiting 0
tee-to-file content:
pollForEndMarker still waiting 0
tee-to-file content:
pollForEndMarker still waiting 0
tee-to-file content:
pollForEndMarker still waiting 0
    1) should get default namespace via ibmcloud kui kubectl


  0 passing (1m)
  1 failing

  1) ibmcloud kui
       should get default namespace via ibmcloud kui kubectl:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/root/amit_sadaphule/kui/node_modules/@kui-shell/plugin-kubectl/dist/test/k8s-popup/a-ibmcloud-plugin.js)
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)



npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @kui-shell/test@8.12.2 testv2: `./bin/runMochaLayersv2.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @kui-shell/test@8.12.2 testv2 script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-10-27T13_15_23_249Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kui-shell@8.12.0 testv2: `export MONOREPO_MODE=true; cd packages/test && npm run testv2`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kui-shell@8.12.0 testv2 script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-10-27T13_15_23_262Z-debug.log
```

**Additional information**

The following commands, when executed manually, do not produce any result either:
```
ibmcloud kui kubectl get pods -A
ibmcloud kui kubectl get default ns
```
Tried adding logs in the test file to see what command gets executed at [this](https://github.com/IBM/kui/blob/master/plugins/plugin-kubectl/src/test/k8s-popup/a-ibmcloud-plugin.ts#L28) line. It showed that the command being executed is:
```
undefined get default ns
```
which does not seem to be correct either.

Please let me know if I am missing something here. Thanks in advance!

**Comment by amitsadaphule** [comment]
Cc @starpit

**Comment by amitsadaphule** [comment]
Can someone please help me on this? Thanks!

**Comment by starpit** [comment]
We have removed the ibmcloud plugin aspects, so this should be good now!
